### ISSUE TITLE
10.3.1 mousedown can block mouseup, click

### ISSUE THREAD

**Issue by mckenzielong** [blackberry/BES10-Cascades#23]
The mousedown event will block the mouseup and click events from firing properly if the dom is modified during a mousedown handler.  I first noticed this while using the Angular Material framework.    You can see an example of this for yourself and log the events in the web inspector at https://material.angularjs.org/0.11.0/#/demo/material.components.button.  Notice that clicking on any button with your finger will only fire the touchstart, touchend, mouseout and mousedown events (in that order.)  This causes unwanted behaviour and seems to block the click event until you 're-click' the button. 

Using the trackpad on the BlackBerry Classic and clicking on a button does trigger the proper events (mousedown, touchstart, mouseup, touchend in that order.)

I reduced this to a small test (http://codepen.io/mckenzielong/pen/MayWwy for running example):

```
  <body>
    <button id="test-button">Block mousedown</button>
    <div></div>
  </body>
```

```
var testButton = document.getElementById("test-button");
testButton.addEventListener("mousedown", function () {
  console.log("Mousedown fired");
  setTimeout(function () {
    console.log("async timeout complete.");
  }, 1000);
  var node = document.createElement("p"); 
    var textnode = document.createTextNode("Water");
    node.appendChild(textnode)
    document.getElementsByTagName("div")[0].appendChild(node);
}, false)

testButton.addEventListener("click", function () {
  console.log("Click fired.");
}, false)

testButton.addEventListener("mouseup", function () {
  console.log("Mouseup fired.");
}, false)
```

**Expected behaviour**: click the button, click fired and mouse up fired messages should be printed to the console.
**Current behaviour**: click and mouseup fire every second button click.

**Comment by timwindsor** [comment]
This is better reported to the Issue Tracker for BB10 at https://www.blackberry.com/jira/browse/BBTEN. They might be able to fix it in 10.3.3, but there are no guarantees.

**Comment by mckenzielong** [comment]
Ah, I see, my mistake.  Jira issue opened here: https://www.blackberry.com/jira/browse/BBTEN-3293  It almost seems like a six or so year old webkit bug that was basically doing the same thing.

Anyway, thanks Tim.  Heres hoping for a resolution in 10.3.3 :+1:

**Comment by timwindsor** [comment]
Yeah, could be something that wasn't pulled in from WebKit.
